local: &local
  adapter: postgresql
  encoding: unicode
  timeout: 5000
  host: localhost
  pool: 25
  username: "<%= ENV['DB_USERNAME'] %>"
  password: "<%= ENV['DB_PASSWORD'] %>"

development: &development
  <<: *local
  database: dcard_crawler_dev

test: &test
  <<: *local
  database: dcard_crawler_test

production:
